### ISSUE TITLE
Eventos-cadastrais/Organizadores (tutor)

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET-visual#103]
Algumas modificacoes:

- Refatoracao de designer
- Juncao da tela de create com de listagem
- Mensagens de erro

**Comment by Confuzo** [comment]
Ao clicar em "Início / Eventos / Organizadores" no canto superior esquerdo logo abaixo de Painel de controle a página recarrega, mas a informação dos organizadores cadastrados some.

O ideal seria voltar pra tela de eventos, não?
