### ISSUE TITLE
Eventos-cadastrais/Participantes (tutor)

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET-visual#104]
Algumas modificacoes:

- Refatoracao de designer
- Juncao da tela de create com de listagem
- Mensagens de erro

**Comment by Confuzo** [comment]
Ao clicar em "Início / Eventos / Participantes" no canto superior esquerdo logo abaixo de Painel de controle a página recarrega, mas a informação dos participantes cadastrados some
