### ISSUE TITLE
Eventos-cadastrais (tutor)

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET-visual#105]
Algumas das modificação nas páginas:

eventos-cadastrais: Excluir coluna status, corrigir search, consertar botão de ativar, modificação de style de titulo, inclusão de spinner ao carregar
eventos-cadastrais/create: Adição de entradas e modificação de designer
-eventos-cadastrais/id : Modificação do designer e do dados mostrados, inclusão de spinner ao carregar
eventos-cadastrais/edit/id: Adição de entradas e modificação de designer e inclusão de spinner ao carregar

**Comment by Confuzo** [comment]
Permite a adição de uma data de rolagem anterior ao início das inscrições. O início da rolagem só deve começar após o fim das inscrições.

Pode se marcar para adicionar anexos, mas não há a opção para efetivamente adicionar
