### ISSUE TITLE
Disciplinas (tutor)

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET-visual#107]
Refeito o designer e implementado as demais funcionalidades

*Envolve todas as pastas relacionadas (create, etc..)

**Comment by Confuzo** [comment]
Criei uma disciplina mas ela não aparece dentro da paginação que aparenta conter um bug (Ao clicar na última página o conteúdo é consumido da api mas não aparece no front). Mesmo problema quando tento me tornar tutor de uma disciplina.

A rota de pesquisa de disciplina está errada.
