### ISSUE TITLE
Quadro-de-tutoria (tutor)

### ISSUE THREAD

**Issue by Samuellucas97** [PETCC-UFRN/ePET-visual#108]
Refeito o designer e implementado as demais funcionalidades

*Envolve todas as pastas relacionadas (create, etc..)

**Comment by Confuzo** [comment]
Eu organizaria as disciplinas pelo seu código e nome, exemplo: FMC1 pode ter muitos tutores ao clicar na disciplina ela me mostraria os tutores dela. Acho que fica mais fácil de usar.

Ao se pesquisar por uma tutoria, independente do método usado ele mostra na tela tutorias que estão desativadas e oferece a opção de desativar novamente. 

Se por acaso só houver uma disciplina e desativar ela a página buga e só mostra os dados novamente após reload.
